name: oculus
region: nyc
services:
  - name: api
    github:
      repo: FSIdevelopment/oculus
      branch: main
      deploy_on_push: true
    source_dir: /backend
    dockerfile_path: backend/Dockerfile
    http_port: 8080
    instance_size_slug: professional-xs
    instance_count: 1
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 1
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: STRIPE_PUBLISHABLE_KEY
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: STRIPE_CONNECT_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: TUNNEL_URL
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: DOCKER_HUB_USERNAME
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: DOCKER_HUB_PAT
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: RESEND_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: POLYGON_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: ALPHAVANTAGE_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: https://oculusalgorithms.com,https://www.oculusalgorithms.com,https://app.oculusalgorithms.com,https://oculus-avvr7.ondigitalocean.app
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      - key: CLAUDE_MAX_TOKENS
        scope: RUN_TIME
        value: "10000"
      - key: TOKENS_PER_ITERATION
        scope: RUN_TIME
        value: "10"
      - key: ADMIN_NAME
        scope: RUN_TIME
        value: Admin
      - key: ADMIN_EMAIL
        scope: RUN_TIME
        value: admin@oculusalgorithms.com
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
    routes:
      - path: /api

  - name: web
    github:
      repo: FSIdevelopment/oculus
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_size_slug: professional-xs
    instance_count: 1
    health_check:
      http_path: /
      initial_delay_seconds: 15
      period_seconds: 10
      timeout_seconds: 1
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: BUILD_TIME
        value: ""
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        scope: BUILD_TIME
        type: SECRET
        value: PLACEHOLDER_ROTATE_ME
    routes:
      - path: /

databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-1vcpu-1gb
    num_nodes: 1
