'use client'

import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-text">
      {/* Header */}
      <div className="bg-surface border-b border-border sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center gap-4">
          <Link
            href="/"
            className="flex items-center gap-2 text-text-secondary hover:text-text transition-colors"
          >
            <ArrowLeft size={20} />
            <span>Back</span>
          </Link>
          <h1 className="text-2xl font-bold">Terms of Use</h1>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-12">
        <div className="prose prose-invert max-w-none space-y-8">
          {/* Last Updated */}
          <p className="text-text-secondary text-sm">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>

          {/* 1. Acceptance of Terms */}
          <section>
            <h2 className="text-2xl font-bold text-text mb-4">1. Acceptance of Terms</h2>
            <p className="text-text-secondary leading-relaxed">
              By accessing and using the Oculus Strategy Platform (&quot;Platform&quot;), you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the Platform. We reserve the right to modify these terms at any time, and your continued use of the Platform constitutes acceptance of any changes.
            </p>
          </section>

          {/* 2. Service Description */}
          <section>
            <h2 className="text-2xl font-bold text-text mb-4">2. Service Description</h2>
            <p className="text-text-secondary leading-relaxed">
              Oculus is an AI-powered trading strategy design and optimization platform. The Platform enables users to create, test, build, and deploy algorithmic trading strategies. Services include strategy generation, backtesting, marketplace access, and strategy deployment via containerized Docker images.
            </p>
          </section>

          {/* 3. Intellectual Property Rights */}
          <section>
            <h2 className="text-2xl font-bold text-text mb-4">3. Intellectual Property Rights</h2>
            <p className="text-text-secondary leading-relaxed mb-4">
              <strong>Ownership:</strong> All algorithms, strategies, code, and intellectual property generated by the Oculus Platform are the exclusive intellectual property of Oculus Algorithms (Forefront Solutions Inc). This includes but is not limited to:
            </p>
            <ul className="list-disc list-inside text-text-secondary space-y-2 ml-4">
              <li>AI-generated trading algorithms</li>
              <li>Strategy optimization logic</li>
              <li>Platform infrastructure and code</li>
              <li>Backtesting engines and data processing systems</li>
            </ul>
            <p className="text-text-secondary leading-relaxed mt-4">
              <strong>User License:</strong> Users are granted a limited, non-exclusive, non-transferable license to use strategies generated by the Platform for personal trading purposes only. This license does not grant ownership of the underlying algorithms or code.
            </p>
            <p className="text-text-secondary leading-relaxed mt-4">
              <strong>Commercial Use:</strong> Any commercial use, redistribution, or deployment of strategies outside the Platform requires explicit written permission from Oculus Algorithms. Unauthorized commercial use is strictly prohibited.
            </p>
          </section>

          {/* 4. License Terms */}
          <section>
            <h2 className="text-2xl font-bold text-text mb-4">4. License Terms</h2>
            <p className="text-text-secondary leading-relaxed mb-4">
              Strategies are delivered as containerized Docker images with built-in license enforcement mechanisms:
            </p>
            <ul className="list-disc list-inside text-text-secondary space-y-2 ml-4">
              <li><strong>IP Tracking:</strong> All strategy containers include IP-based license verification to ensure authorized use only</li>
              <li><strong>Annual Licensing:</strong> Commercial licenses are issued on an annual basis and require renewal</li>
              <li><strong>Container Integrity:</strong> Modification, reverse engineering, or tampering with strategy containers is strictly prohibited</li>
              <li><strong>Redistribution:</strong> Unauthorized redistribution of strategy containers to third parties is prohibited</li>
            </ul>
            <p className="text-text-secondary leading-relaxed mt-4">
              Violation of these license terms may result in immediate account termination and legal action.
            </p>
          </section>

          {/* 5. Marketplace Revenue Sharing */}
          <section>
            <h2 className="text-2xl font-bold text-text mb-4">5. Marketplace Revenue Sharing</h2>
            <p className="text-text-secondary leading-relaxed mb-4">
              Users who publish strategies to the Oculus Marketplace agree to the following revenue sharing model:
            </p>
            <ul className="list-disc list-inside text-text-secondary space-y-2 ml-4">
              <li><strong>Platform Fee:</strong> 35% of all subscription revenue</li>
              <li><strong>Creator Revenue:</strong> 65% of all subscription revenue</li>
            </ul>
            <p className="text-text-secondary leading-relaxed mt-4">
              Revenue is calculated based on active subscriptions to your published strategies. Payments are processed monthly and subject to our payment terms.
            </p>
            <p className="text-text-secondary leading-relaxed mt-4">
              Marketplace payouts to strategy creators are processed via Stripe Connect. To receive payouts, you must complete Stripe Connect onboarding and provide the necessary banking and identity information required by Stripe.
            </p>
          </section>

          {/* 6. Payment Terms */}
          <section>
            <h2 className="text-2xl font-bold text-text mb-4">6. Payment Terms</h2>
            <p className="text-text-secondary leading-relaxed mb-4">
              <strong>Token Purchases:</strong> All token purchases are non-refundable. Tokens are used to access Platform features and services.
            </p>
            <p className="text-text-secondary leading-relaxed mb-4">
              <strong>Subscription Billing:</strong> Subscription charges are recurring and will continue until you cancel your subscription. Cancellation must be requested through your account settings. Refunds for partial billing periods are not available.
            </p>
            <p className="text-text-secondary leading-relaxed">
              <strong>Payment Methods:</strong> We accept payment via credit card and other methods as specified during checkout. All payments, subscriptions, and marketplace payouts are processed through Stripe. Personal and financial information provided during payment is shared with Stripe in accordance with their privacy policy.
            </p>
          </section>

          {/* 7. Data & Privacy */}
          <section>
            <h2 className="text-2xl font-bold text-text mb-4">7. Data & Privacy</h2>
            <p className="text-text-secondary leading-relaxed mb-4">
              <strong>Data Collection:</strong> The Platform collects usage data including but not limited to:
            </p>
            <ul className="list-disc list-inside text-text-secondary space-y-2 ml-4">
              <li>Strategy creation and modification history</li>
              <li>Backtesting parameters and results</li>
              <li>Platform feature usage analytics</li>
              <li>Account activity and login information</li>
            </ul>
            <p className="text-text-secondary leading-relaxed mt-4">
              <strong>Trading Data:</strong> Trading data is processed to generate and optimize strategies. Data is not stored beyond what is necessary for strategy generation and performance analysis. Historical trading data may be retained for up to 12 months for analytics purposes.
            </p>
            <p className="text-text-secondary leading-relaxed mt-4">
              <strong>Data Security:</strong> We implement industry-standard security measures to protect your data. However, no system is completely secure, and we cannot guarantee absolute security.
            </p>
            <p className="text-text-secondary leading-relaxed mt-4">
              <strong>Personal Information for Marketplace Payouts:</strong> Users who publish strategies to the marketplace are required to provide personal information (including legal name, address, date of birth, and banking details) to set up payout accounts. This information is collected for internal use only — solely to process marketplace payouts. Payout processing is handled through Stripe Connect; personal information is shared with Stripe for this purpose. Oculus does not sell, rent, or share personal information collected for payout processing with any third parties other than Stripe.
            </p>
          </section>

          {/* 8. Limitation of Liability */}
          <section>
            <h2 className="text-2xl font-bold text-text mb-4">8. Limitation of Liability</h2>
            <p className="text-text-secondary leading-relaxed mb-4">
              <strong>No Financial Advice:</strong> The Oculus Platform and all strategies provided are not financial advice. Users are solely responsible for their trading decisions and should consult with a qualified financial advisor before making investment decisions.
            </p>
            <p className="text-text-secondary leading-relaxed mb-4">
              <strong>Past Performance:</strong> Past performance of strategies does not guarantee future results. Market conditions change, and strategies may not perform as expected in different market environments.
            </p>
            <p className="text-text-secondary leading-relaxed mb-4">
              <strong>Liability Disclaimer:</strong> Oculus Algorithms is not liable for:
            </p>
            <ul className="list-disc list-inside text-text-secondary space-y-2 ml-4">
              <li>Trading losses or financial damages resulting from strategy use</li>
              <li>Market volatility or unexpected price movements</li>
              <li>Technical failures or platform downtime</li>
              <li>Data loss or corruption</li>
              <li>Third-party service failures (exchanges, data providers, etc.)</li>
            </ul>
            <p className="text-text-secondary leading-relaxed mt-4">
              In no event shall Oculus Algorithms be liable for any indirect, incidental, special, or consequential damages.
            </p>
          </section>

          {/* 9. Termination */}
          <section>
            <h2 className="text-2xl font-bold text-text mb-4">9. Termination</h2>
            <p className="text-text-secondary leading-relaxed mb-4">
              Oculus Algorithms reserves the right to terminate or suspend your account at any time for:
            </p>
            <ul className="list-disc list-inside text-text-secondary space-y-2 ml-4">
              <li>Violation of these Terms of Use</li>
              <li>Unauthorized use or redistribution of strategies</li>
              <li>Reverse engineering or tampering with Platform code</li>
              <li>Fraudulent activity or payment disputes</li>
              <li>Violation of applicable laws or regulations</li>
              <li>Abuse of Platform resources</li>
            </ul>
            <p className="text-text-secondary leading-relaxed mt-4">
              Upon termination, your access to the Platform will be immediately revoked, and any active licenses will be invalidated.
            </p>
          </section>

          {/* 10. Modifications to Terms */}
          <section>
            <h2 className="text-2xl font-bold text-text mb-4">10. Modifications to Terms</h2>
            <p className="text-text-secondary leading-relaxed">
              We may update these Terms of Use at any time. Changes will be effective immediately upon posting to the Platform. Your continued use of the Platform following any changes constitutes your acceptance of the new terms. We encourage you to review these terms periodically.
            </p>
          </section>

          {/* Contact */}
          <section className="mt-12 pt-8 border-t border-border">
            <h2 className="text-2xl font-bold text-text mb-4">Contact Us</h2>
            <p className="text-text-secondary leading-relaxed">
              If you have questions about these Terms of Use, please contact us at support@oculusalgorithms.com
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}

